In [120]:
import pandas as pd

In [122]:
df=pd.read_csv(r"C:\Users\LAKA\Downloads\Compressed\archive_5\spotify_millsongdata.csv")

In [124]:
df.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [126]:
df.shape

(57650, 4)

In [128]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [130]:
df= df.sample(5000).drop('link', axis=1).reset_index(drop=True)

In [132]:
df['text'][0]

"Here comes the water.  \r\nAll I knew and all I believed  \r\nare crumbling images  \r\nthat no longer comfort me.  \r\nI scramble to reach higher ground,  \r\nsome order and sanity,  \r\nor something to comfort me.  \r\nSo I take what is mine, and hold what is mine,  \r\nsuffocate what is mine, and bury what's mine.  \r\nSoon the water will come  \r\nand claim what is mine.  \r\nI must leave it behind,  \r\nand climb to a new place now.  \r\nThis ground is not the rock I thought it to be.  \r\nThought I was high, and free.  \r\nI thought I was there  \r\ndivine destiny.  \r\nI was wrong.  \r\nThis changes everything.  \r\nThe water is rising up on me.  \r\nThought the sun would come deliver me,  \r\nbut the truth has come to punish me instead.  \r\nThe ground is breaking down right under me.  \r\nCleanse and purge me  \r\nin the water.  \r\n\r\n"

In [135]:
df.shape

(5000, 3)

In [137]:
#Text cleaning
df['text']= df['text'].str.lower().replace(r'^\w\s','').replace(r'\n', ' ', regex= True)

In [141]:
df.tail(5)

,artist,song,text
4995,Roxy Music,Rain Rain Rain,you better take what's left \r 'cause i'm fee...
4996,Elton John,Island Girl,"i see your teeth flash, jamaican honey so swee..."
4997,Alabama,Old (Baugh) Road,'round 'ole' baugh road it's a great place kid...
4998,Isley Brothers,Eternal,i love you \r i love you \r and this is eter...
4999,Misfits,Speak Of The Devil,traded in my bible for a little black cat \r ...

In [143]:
import nltk
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize

In [145]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LAKA\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [147]:
import nltk
print(nltk.data.path)

['C:\\Users\\LAKA/nltk_data', 'C:\\Users\\LAKA\\anaconda3\\nltk_data', 'C:\\Users\\LAKA\\anaconda3\\share\\nltk_data', 'C:\\Users\\LAKA\\anaconda3\\lib\\nltk_data', 'C:\\Users\\LAKA\\AppData\\Roaming\\nltk_data', 'C:\\nltk_data', 'D:\\nltk_data', 'E:\\nltk_data']

In [149]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LAKA\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [152]:
stemmer = PorterStemmer()

In [154]:
def token(txt):
    token = nltk.word_tokenize(txt)
    a= [stemmer.stem(w) for w in token]
    return " ".join(a)

LookupError:
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - 'C:\\Users\\LAKA/nltk_data'
    - 'C:\\Users\\LAKA\\anaconda3\\nltk_data'
    - 'C:\\Users\\LAKA\\anaconda3\\share\\nltk_data'
    - 'C:\\Users\\LAKA\\anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\LAKA\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

In [158]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [160]:
tfid= TfidfVectorizer(analyzer='word', stop_words='english')

In [162]:
matrix=tfid.fit_transform(df['text'])

In [164]:
similer=cosine_similarity(matrix)

In [166]:
similer[0]

array([1.        , 0.00382822, 0.05164182, ..., 0.003804  , 0.01053675,
       0.01824787])

In [182]:
df[df['song']=='Speak Of The Devil'].index[0]

4999

**Recommender function**

In [185]:
def recommender(song_name):
    idx = df[df['song']=='Waiting For The Man'].index[0]
    distance = sorted(list(enumerate(similer[idx])), reverse=True, key= lambda x:x[1])
    song= []
    for s_id in distance[1:5]:
        song.append(df.iloc[s_id[0]].song)
    return song

In [187]:
df.head(10)

,artist,song,text
0,Tool,Flood,here comes the water. \r all i knew and all i...
1,Great Big Sea,Captain Kidd,[chorus] \r my name is captain kidd \r as i ...
2,Louis Armstrong,Bill Bailey,"won't you come home, bill bailey, won't you co..."
3,Hillsong,For Who You Are,standing here in your presence \r thinking of...
4,Tom T. Hall,I Love,"i love little baby ducks, old pickup trucks \..."
5,Mariah Carey,It's Like That,"dis is, the point when i need everybody get to..."
6,R. Kelly,Kickin It With Your Girlfriend,[chorus] \r i've been kicking it with your gi...
7,Hillsong United,God Is Moving,"holy spirit, touch your people \r teach us th..."
8,Selena Gomez,Falling Down,"uh, oh oh, oh \r uh, oh oh, oh \r uh, oh oh,..."
9,Incubus,Let's Go Crazy,dearly beloved \r we are gathered here today ...

IndexError: index 0 is out of bounds for axis 0 with size 0

In [195]:
import pickle

In [198]:
pickle.dump(similer,open("similarity", "wb"))

In [200]:
pickle.dump(df, open("df", "wb"))